# ref: https://jupyterbook.org/en/stable/customize/config.html

title: "Does inflation have an impact on stock prices?"
author: Kunwoo Kim
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
